import {useCallback, useState} from 'react';
import useSWR from 'swr'
import {useRouter} from 'next/router';
import Head from "next/head"
import Image from "next/image"
import {useAuth} from '../features/auth';
import styles from "./PhoneList.module.css";
import Link from 'next/link';

const PhoneList = () => {
  const auth = useAuth();
  const [selectedPhone, selectPhone] = useState<Device | null>(null);
  const onSelectPhone = useCallback((device: Device) => {
    selectPhone(device);
  }, [selectPhone]);
  if (!auth.session) return null;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.sidebar}>
        <PhonesList device={selectedPhone} onSelectPhone={onSelectPhone} />
      </div>

      <main className={styles.main}>
        <p className={styles.description}>
          <Link href="/">Главная</Link>
        </p>
        {selectedPhone && <SmsList device={selectedPhone} />}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default PhoneList

interface PhoneListProps {
  onSelectPhone: (device: Device) => void,
  device: Device | null
}
function PhonesList({device, onSelectPhone}: PhoneListProps) {
  const {data} = useSWR('phone_list', () => searchDevice());
  const onSelect = useCallback((device: Device) => {
    onSelectPhone(device);
  }, [onSelectPhone]);
  return (
    <ul className={styles.list}>
      {data?.map(d => (
        <li
          key={d.phoneNumber}
          onClick={() => onSelect(d)}
        >
          {d.phoneNumber === device?.phoneNumber && 'V '}{d.phoneNumber}
        </li>
      ))}
    </ul>
  )
}

interface SearchDevice {
  mobileNumber: string
}
type Device = SearchDevice & {phoneNumber: string};

function searchDevice(params: any = {page: 1}): Promise<Device[]> {
  const opts: RequestInit = {
    body: JSON.stringify(params),
    method: 'post',
    credentials: 'include',
    headers: {
      'Content-Type': 'application/json'
    }
  };
  return fetch(`${process.env.SMS_READER_API}/device/search`, opts)
    .then(r => r.json()).then((data) => data.map((d: any) => ({...d, phoneNumber: formatPhone(d)})));
}

function formatPhone(device: SearchDevice) {
  return `+${device.mobileNumber}`;
}

function smsSearch(params: SearchDevice): Promise<Array<{content: string, id: string}>> {
  const opts: RequestInit = {
    body: JSON.stringify(params),
    method: 'post',
    credentials: 'include',
    headers: {
      'Content-Type': 'application/json'
    }
  };
  return fetch(`${process.env.SMS_READER_API}/device/sms/search`, opts)
    .then(r => r.json())
    // @ts-ignore
    .then((data) => data.map(({_id, ...d}) => ({...d, id: _id})));
}

function SmsList({device}: {device: Device}) {
  const params = {mobileNumber: device.mobileNumber};
  const {data} = useSWR(`${device.mobileNumber}`, () => smsSearch(params));
  return (
    <ul>
      {data?.map((sms) => (
        <li key={sms.id}>
          {sms.content}
        </li>
      ))}
    </ul>
  );
}
