import Head from "next/head"
import Image from "next/image"
import {useAuth} from '../features/auth';
import styles from "./PhoneList.module.css";
import Link from 'next/link';

const PhoneList = () => {
  const auth = useAuth();
  if (!auth.session) return null;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.sidebar}>
        <ul>
          <li>78883330044</li>
          <li>79992220033</li>
        </ul>
      </div>

      <main className={styles.main}>
        <p className={styles.description}>
          <Link href="/">Главная</Link>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default PhoneList
